[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
ethprim_lib = "HswLWCKuBrz93fRxWNoU8yAsuUyvsntteXxDaWmU9KFy"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/davidkathoh/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
